name: DORAK
description: A family party game inspired by Seen Jeem
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.3.2
  google_sign_in: ^5.3.2
  sign_in_with_apple: ^6.1.0
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  provider: ^6.1.1
  share_plus: ^7.0.1
  audioplayers: ^5.2.1
  sensors_plus: ^5.0.1
  http: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/audio/
    - lib/l10n/app_en.arb
    - lib/l10n/app_ar.arb

l10n:
  arb-dir: lib/l10n
  template-arb-file: app_en.arb
